name: Run Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook nbconvert nbformat

    - name: Run Jupyter Notebooks
      env:  # Add your environment variables here
        DEVTOAPI: ${{ secrets.DEVTOAPI }}
      run: |
        for notebook in $(find . -name "*.ipynb"); do
          echo "Running $notebook"
          jupyter nbconvert --to notebook --execute "$notebook" --output "$notebook"
        done
